---
version: "3.8"
services:
  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: datasynthesis
    # volumes:
    #   - MySQL-DDL/datasynthesis-2020-0924.sql:/docker-entrypoint-initdb.d/001.sql:Z,delegated
    #   - MySQL-DumpFiles/complete-datasynthesis-08222020.sql:/docker-entrypoint-initdb.d/002.sql:Z,delegated

